vim.loader.enable()

-- If you previously used native packages (Packer, manual pack/*/start), Neovim will
-- auto-load anything under stdpath('data')/site/pack/*/start.
-- Since this config is now fully lazy.nvim-managed, remove that packpath to avoid
-- double-loading old plugins (e.g. packer.bak leftovers).
vim.opt.packpath:remove(vim.fn.stdpath("data") .. "/site")

require("config.python_host_prog")
require("config.options")
require("config.keymaps")
require("config.plugins")
require("config.cmp")
require("config.lsp")
require("config.dap")
require("config.telescope-setup")
require("config.treesitter")
require("config.autopairs")
require("config.comment")
require("config.gitsigns")
require("config.nvim-tree")
require("config.bufferline")
require("config.lualine")
require("config.toggleterm")
-- require("config.project")
require("config.illuminate")
require("config.indentline")
require("config.alpha")
require("config.whichkey")
require("config.autocommands")
require("config.transparent")
require("config.monokaitheme")
require("config.colorscheme")
-- require("config.monokaipro")
require("config.iron")
require("config.jupytext")
require("config.colorizer")
require("config.smartcc")
require("config.vimtex")
require("config.glow")
require("config.osc52")
require("config.markdown")
-- require("config.minuerai")
require("config.macro")
require("config.cmd")
